In [ ]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('/content/final_dataset.csv')

# Display the first 5 rows
df.head()

                                                text     emotion
0  i feel rather funny ending with so many dupes ...         fun
1                     i feel surprised by the result    surprise
2                    i am officially feeling festive     neutral
3  i suddenly found myself standing before this w...    surprise
4  i look at the meager pile of food i purchased ...  enthusiasm

In [ ]:
# Check the column names and data types
print(df.dtypes)

text       object
emotion    object
dtype: object

In [ ]:
# Create a comparison table
comparison = pd.DataFrame({
    'Original Text': df['text'].head(),
    'Lowercase Text': df['text'].str.lower().head()
})

comparison

,Original Text,Lowercase Text
0,i feel rather funny ending with so many dupes ...,i feel rather funny ending with so many dupes ...
1,i feel surprised by the result,i feel surprised by the result
2,i am officially feeling festive,i am officially feeling festive
3,i suddenly found myself standing before this w...,i suddenly found myself standing before this w...
4,i look at the meager pile of food i purchased ...,i look at the meager pile of food i purchased ...

In [ ]:
# Tokenization without NLTK and without loops

df['tokens'] = df['text'].astype(str).str.split()

# Display first 5 samples
df[['text', 'tokens']].head()

,text,tokens
0,i feel rather funny ending with so many dupes ...,"[i, feel, rather, funny, ending, with, so, man..."
1,i feel surprised by the result,"[i, feel, surprised, by, the, result]"
2,i am officially feeling festive,"[i, am, officially, feeling, festive]"
3,i suddenly found myself standing before this w...,"[i, suddenly, found, myself, standing, before,..."
4,i look at the meager pile of food i purchased ...,"[i, look, at, the, meager, pile, of, food, i, ..."

In [ ]:
print(df.columns)

Index(['text', 'emotion', 'tokens'], dtype='object')

In [ ]:
import nltk
from nltk.corpus import stopwords

# Download stopwords (run once)
nltk.download('stopwords')

# Load English stopwords
stop_words = set(stopwords.words('english'))

# Remove stopwords from the tokenized text
df['tokens_no_stopwords'] = df['tokens'].apply(
    lambda words: [word for word in words if word.lower() not in stop_words]
)

# Display before and after results for first 5 samples
df[['tokens', 'tokens_no_stopwords']].head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

,tokens,tokens_no_stopwords
0,"[i, feel, rather, funny, ending, with, so, man...","[feel, rather, funny, ending, many, dupes, alw..."
1,"[i, feel, surprised, by, the, result]","[feel, surprised, result]"
2,"[i, am, officially, feeling, festive]","[officially, feeling, festive]"
3,"[i, suddenly, found, myself, standing, before,...","[suddenly, found, standing, woman, dressed, li..."
4,"[i, look, at, the, meager, pile, of, food, i, ...","[look, meager, pile, food, purchased, week, fe..."

In [ ]:
import nltk
from nltk.stem import PorterStemmer

# Create Porter Stemmer object
ps = PorterStemmer()

# Apply stemming
df['stemmed_tokens'] = df['tokens_no_stopwords'].apply(
    lambda words: [ps.stem(word) for word in words]
)

# Display stemmed output for first 10 samples
df[['tokens_no_stopwords', 'stemmed_tokens']].head(10)

,tokens_no_stopwords,stemmed_tokens
0,"[feel, rather, funny, ending, many, dupes, alw...","[feel, rather, funni, end, mani, dupe, alway, ..."
1,"[feel, surprised, result]","[feel, surpris, result]"
2,"[officially, feeling, festive]","[offici, feel, festiv]"
3,"[suddenly, found, standing, woman, dressed, li...","[suddenli, found, stand, woman, dress, like, p..."
4,"[look, meager, pile, food, purchased, week, fe...","[look, meager, pile, food, purchas, week, feel..."
5,"[I,, one,, thrilled, Christ, works, outside, t...","[i,, one,, thrill, christ, work, outsid, time-..."
6,"[hate, power, make, feel, ugly, things]","[hate, power, make, feel, ugli, thing]"
7,"[feel, like, missed]","[feel, like, miss]"
8,"[personally, experienced, gut, wrenching, feel...","[person, experienc, gut, wrench, feel, kick, l..."
9,"[hate, feeling, people, see, ugly, know, got, ...","[hate, feel, peopl, see, ugli, know, got, some..."

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer

# Download WordNet resources (run once)
nltk.download('wordnet')
nltk.download('omw-1.4')

# Create lemmatizer object
lemmatizer = WordNetLemmatizer()

# Apply lemmatization
df['lemmatized_tokens'] = df['tokens_no_stopwords'].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

# Compare stemming and lemmatization results
df[['tokens_no_stopwords', 'stemmed_tokens', 'lemmatized_tokens']].head(10)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

,tokens_no_stopwords,stemmed_tokens,lemmatized_tokens
0,"[feel, rather, funny, ending, many, dupes, alw...","[feel, rather, funni, end, mani, dupe, alway, ...","[feel, rather, funny, ending, many, dupe, alwa..."
1,"[feel, surprised, result]","[feel, surpris, result]","[feel, surprised, result]"
2,"[officially, feeling, festive]","[offici, feel, festiv]","[officially, feeling, festive]"
3,"[suddenly, found, standing, woman, dressed, li...","[suddenli, found, stand, woman, dress, like, p...","[suddenly, found, standing, woman, dressed, li..."
4,"[look, meager, pile, food, purchased, week, fe...","[look, meager, pile, food, purchas, week, feel...","[look, meager, pile, food, purchased, week, fe..."
5,"[I,, one,, thrilled, Christ, works, outside, t...","[i,, one,, thrill, christ, work, outsid, time-...","[I,, one,, thrilled, Christ, work, outside, ti..."
6,"[hate, power, make, feel, ugly, things]","[hate, power, make, feel, ugli, thing]","[hate, power, make, feel, ugly, thing]"
7,"[feel, like, missed]","[feel, like, miss]","[feel, like, missed]"
8,"[personally, experienced, gut, wrenching, feel...","[person, experienc, gut, wrench, feel, kick, l...","[personally, experienced, gut, wrenching, feel..."
9,"[hate, feeling, people, see, ugly, know, got, ...","[hate, feel, peopl, see, ugli, know, got, some...","[hate, feeling, people, see, ugly, know, got, ..."

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Convert token lists back to sentences
corpus = df['lemmatized_tokens'].apply(lambda x: ' '.join(x))

# Create CountVectorizer object
vectorizer = CountVectorizer()

# Fit and transform the text data
X = vectorizer.fit_transform(corpus)

# Display Vocabulary
print("Vocabulary:")
print(vectorizer.vocabulary_)

# Display Feature Names
print("\nFeature Names:")
print(vectorizer.get_feature_names_out())

# Display BoW Matrix
print("\nBag of Words Matrix:")
print(X.toarray())

# Display Shape
print("\nShape of Matrix:")
print(X.shape)

Vocabulary:

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Convert lemmatized tokens back to sentences
corpus = df['lemmatized_tokens'].apply(lambda x: ' '.join(x))

# Create TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the text data
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

# Display Vocabulary
print("Vocabulary:")
print(tfidf_vectorizer.vocabulary_)

# Display TF-IDF Matrix
print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())

# Display Shape
print("\nShape of TF-IDF Matrix:")
print(tfidf_matrix.shape)

Vocabulary:

Feature Names:
['00' '000' '000calories' ... 'เขาจะเผาม' 'ℕoíʀ' 'ㄒʜℰℳℰ']